name: CI

on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Get date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash # For Windows, Linux and macOS default to bash already
    # This version of the cache stores one entry per day and relies on checkout to pull the necessary changes.
    #- name: Cache .git folder
    #  uses: actions/cache@v1
    #  with:
    #    path: .git/
    #    key: git-${{ steps.get-date.outputs.date }}
    #    restore-keys: |
    #      git-
    # This version of the cache has more "churn" as it caches each commit.
    - name: Cache .git folder
      uses: actions/cache@v1
      with:
        path: .git/
        key: git-${{ github.sha }}
        restore-keys: |
          git-
    - uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: Use node version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- name: Cache dependencies
    #  uses: actions/cache@v1
    #  with:
    #    path: ~/.npm
    #    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    #    restore-keys: |
    #      ${{ runner.os }}-node-
    - name: Remove existing TypeScript
      run: |
        npm uninstall typescript --no-save
        npm uninstall tslint --no-save
    - name: npm install and test
      run: |
        npm install
        npm update
        npm test
